### ISSUE TITLE
Gundam Models too big to print

### ISSUE THREAD

**Issue by PliskinOrgasmo** [madrod228/voicesoftheprinter#36]
no idea who even made those models, but somehow they made them too big to even print

**Comment by KillerBlade555** [comment]
Follow this Guide to print them https://github.com/madrod228/voicesoftheprinter/blob/main/Guide-Bypass%20Limit%20and%20Speedprinting.md

**Comment by PliskinOrgasmo** [comment]
or just make normal sized versions instead?

**Comment by KillerBlade555** [comment]
These were made with the Bypass in mind. If you dont want to do the bypass, you'll have to resize it in blender. If you're trying to print the ones from page 36 they should have a desk version included. Rename the PNG to match the desk size version.
I.E. XXXG-01D2GundamDeathScytheHell to Desk Size XXXG-01D2GundamDeathScytheHell. All of them should have a desk size version except Heavy Arms
